# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45a11ab170b809bc463b1fdbf03e4e162b6e7603d01262e45e444dc47b1cba6d75d18a42a4ef6769feb6a81692ba8ea661dabdfebe318c7dd019af26ec447977

test:
  secret_key_base: a9628bc8467f7b98034990ab19db425305cc961750ddc5a144c9bc60ffb6040e55aa587cc210d0a205a8205fc8035d7cfaa0f6cf01e26adadc0c99251e4d0dbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
